title: "Vinay Kanigicherla"
author: "Vinay Kanigicherla"
description: "© 2023 Vinay Kanigicherla"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true       # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "bio.md", title: "Bio"}
#   - {file: "project.html", title: "Projects"}
#   - {file: "blog.html", title: "Blog"}
#   - {url: "https://drive.google.com/file/d/178Y70_ys1A6rCs5OK0CgsnDzjEjvyxyY/view?usp=sharing", title: "Resume"}
 

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/in/vinaykanigicherla/"}
  - {title: Github, icon: github, url: "https://github.com/vinaykanigicherla"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/VinKanigicherla"}
  - {title: Instagram, icon: instagram, url: "https://www.instagram.com/vinaykanigicherla/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
